// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxGUFNFwnHY04olB4W5C8_cBtQt3gxTCE',
    appId: '1:300699130742:web:cd5fed4cd612a60935b857',
    messagingSenderId: '300699130742',
    projectId: 'stayhub-8ff9f',
    authDomain: 'stayhub-8ff9f.firebaseapp.com',
    storageBucket: 'stayhub-8ff9f.firebasestorage.app',
    measurementId: 'G-HSHP1RMSFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWjG-yaNebBAXGjJhLhWCSG_JTku7lLfI',
    appId: '1:300699130742:android:3b6d00f2e659715435b857',
    messagingSenderId: '300699130742',
    projectId: 'stayhub-8ff9f',
    storageBucket: 'stayhub-8ff9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXYK_yRiJtCWfT5sXJvDFR0Dxng1mp_1w',
    appId: '1:300699130742:ios:fe051de3c9bb709735b857',
    messagingSenderId: '300699130742',
    projectId: 'stayhub-8ff9f',
    storageBucket: 'stayhub-8ff9f.firebasestorage.app',
    iosBundleId: 'com.stayhub.stayhubMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXYK_yRiJtCWfT5sXJvDFR0Dxng1mp_1w',
    appId: '1:300699130742:ios:fe051de3c9bb709735b857',
    messagingSenderId: '300699130742',
    projectId: 'stayhub-8ff9f',
    storageBucket: 'stayhub-8ff9f.firebasestorage.app',
    iosBundleId: 'com.stayhub.stayhubMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxGUFNFwnHY04olB4W5C8_cBtQt3gxTCE',
    appId: '1:300699130742:web:1360de760345287335b857',
    messagingSenderId: '300699130742',
    projectId: 'stayhub-8ff9f',
    authDomain: 'stayhub-8ff9f.firebaseapp.com',
    storageBucket: 'stayhub-8ff9f.firebasestorage.app',
    measurementId: 'G-VJ2313ME6D',
  );
}
